language: node_js
node_js: stable
before_install:
- stty cols 80
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
env:
  global:
  - secure: SwUIwkmZW3oWoIcM5c50R0Bft9qmEM70hq1RQ54Pv66WJw77bIcacMB04bvcK63WlKXrz9Cu5X5ugy8sxUtqSz7ec9R3g+yBqwNCE3a3VcR8DujlJDNNvIEWOI9gin0Ohna+ugQm/oj5ltaGrjFfZeAtK084VVJyFpFlo/tQfCoS0rY3lQuwHdDh1vhmdF20j4RnsI8LBT1RHOL4zSo/JogXdoXQoW8b4W8CgN10aa2W2LRUufh657X6e6UK6Mpe5UnS+GXuq5xG28Br0bWLcZG6HH8lKwIgzUinvDhGt03Xre0pusRxzCTnSMgRfNqrhlTAC3CurCV+rxDSwZwCexIfoynFrmlrTjL1WaxXaXxwVEiBQYVS5QhEU9pVoQnwz6RMs0nxJLVfbQxVLmB0xPChz+xYLK8ILqjEsnxCdVwlVs7MA5u2a62ahicMfWK3VpoYn7T/cf+jkHaOxP5A7p7YcYVlPphw6bncEFX7bqCHlD0q1c8QkZeQaFzuf++2Gm2l1gXAV8oF8ac276t07fzy4/Z+9OPcCUC8KJb90nOzFYCdvfJhJ5OP3s7rosdVk3szISfistNjCzK5bpWbDbl3d3kXlW91GjAys9YDdlq3vkc74+nuSezpLehmbE68WwjkCiHigab0TSQXcATz2u4h64XlVuUL+7/7UBTAgmk=
  - secure: APeUipxW92xaKoHOIfR/uWYZoHpAcqbaGokvh3OKdEfdKyKENV6pHBoYg4Wsy6kdfuT7JBIErhn4892dzwE7BaMkg0W07HZMugM8MVO3qjctM3I4bqKjzmpyueFMJuc+XXXEPYIwpCeCl1v42VSl8txO9LTMsFtW8TKnxAnm+28p3U0d2jVB3AY5vhlxUB3QzaJN7MPo88vbhuCfnC8ZWvlkfRilW4IYbPE3GXHT2nstSs0jIID5sfPASCh2Pvns9yldqUKFMPB8yl1GwKkjlHEZcTtjbPXruUZ9dAIXH4NmgZIZuSyNBG7HgDu/tS8gusFkMuWOahX6Ynjl5yxhlwX5AomhxJV4+5w6uCEE9L/WeK8yyd439H7L/7jXUWmOBFVhx72TjRpq94hwdl2XWXlgFvJVffTvY92/XbesgwpkwHEtlqKKyZX+sfwGOiBBzpdlVGOG+Lu5JuvTt2TqU0RDth9xxTNIOTqPWHTBcOqMi0ZjWk40yVpeuD1Z+JI9XMwd8tvpbhZ0o+3IxIHascZr37CvWQKq0IWsO4kWDJRD8OCXXcDj43ulVcUPxfIAT5Gu0vPZNCIMzx4lC4JPMW0+YnRy1yngcsWTbr1Jd79F2j4RDNdy8JTm7s5ceqIGjV5iRu0scIiHhX0ZLgm6ad2GB3hOhQA+7IwTWQSvBWg=
  - secure: hU1Ljqt+AlekUmNbLMmIx91ssXVghNz8bzLOLKcRZq4SH3nvF0GIFSBbAYN+7GhiSu41+pKadJxDR2CEIjj5lRqTzHMmaZnbCeVv7aoWwAeGuctRdDmi9UhzX8VMxFmhh6XVBukbSAwR4lFJaWGZvwkxm26A0zU/lvwgDS/BcCNQWWvOnfhXlj2qdH/GwYN+dikREgZpoPGskw155H8OOR02aFvej9PzgK5+c6n8QWjVEP+cpL7AUxEKU7BivPA8STyyS5NNIMrNJnCDzSoV5DxzCXQK24woMYVwIEHFvlBzz3vtegYtLHhqA2O/W0SIwpJ/U5cxOcqgAdyC1xJHprgOlMNhK+WA3vwtGsE329AA7FFYpdkOtqd7RmgD2FDVqyDs8/0ABDQ5jzE4hUUDC/zWHtNY9VYwIDENMh3myjmKW5B/dL16mAD5lmKCYT7x5Un0Un10M/HSpSbpdFxo/Dw2598vVBFYc+yvb0VGAYbpKWmVMMDiaBkj2PjFIB0qZ+b9XjFK5UEEavT0qfn2pxQD8IEfp/la9oc0BUD5s1d+JtS6bGf6G4KsXhhJ/8cTMZexQ1qnIFoe0ZN2fY8sHctQfhVXR6sCoWmrb6atZ2nzSZENEa/45t2LuAkb5R+rIdqPRSoE42CA75scCr8jEZG2TEVUreoxCdYYDwz34s8=
