branches:
  only:
  - master
language: node_js
node_js: stable
before_install:
- stty cols 80
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
env:
  global:
  - secure: ZxaTr5XehajTaFZqGL0asmVIL7Hom5GsFlL5r2TjHScYFtAXsEXCzu73Ood5owpMLQiYl/Ryy1o2U/R3HkBXrm93dSGl4BDzbwpumFunTeBPeK0eXDhsDBmTAboortKmqBkOmfPsvISJGK65E5DgCOh5nbVvgOrlEq2sf/DF+qbOFJ+ZHkundkVHkkFpwWSKtC4YlrlSLAUnBXB/ieX+rQF9JzRW52i7yhK0nUzA/dDxX3kAAg4TVH8KshgE8DkOWaLj8kcKnsiSPev7WRbE2Q0XE6wtkqePufq+sfjith+pgttLVP9vEay6pNag4RFLjZxbkcpwXv7x6KlyE7pOamXzjO5vEt+F6Dp0/lLhzKHkq39R8W4GQ1OXqpMI8fRQMfOrQaN2ispsz+liKlivYOTLkzlrS4FI5eT+77VeWaoVzmQeuPbUG+hpTu5MKekmMxLRuVkoJhcc464CztQvK+fnKkuR4QXzuuQ7HOXL5YGXNV2LXesmX+xEN5X1c92EZluoIw9ydQWTZyvPRPTSwM4ghu0yBbHRjAIMAo3aK2yvVmRgWNiQHyu335epK1gFsVzF72JkdWMzVAc81aj4mtD1gEcs3tMSibdMS8pZ4nm0WEuBYPYdconH1B4njzXuM1zhEfDsrqI//NOnR5Z9wj3vTD2hgy0b1uEaUU+Oksg=
  - secure: APeUipxW92xaKoHOIfR/uWYZoHpAcqbaGokvh3OKdEfdKyKENV6pHBoYg4Wsy6kdfuT7JBIErhn4892dzwE7BaMkg0W07HZMugM8MVO3qjctM3I4bqKjzmpyueFMJuc+XXXEPYIwpCeCl1v42VSl8txO9LTMsFtW8TKnxAnm+28p3U0d2jVB3AY5vhlxUB3QzaJN7MPo88vbhuCfnC8ZWvlkfRilW4IYbPE3GXHT2nstSs0jIID5sfPASCh2Pvns9yldqUKFMPB8yl1GwKkjlHEZcTtjbPXruUZ9dAIXH4NmgZIZuSyNBG7HgDu/tS8gusFkMuWOahX6Ynjl5yxhlwX5AomhxJV4+5w6uCEE9L/WeK8yyd439H7L/7jXUWmOBFVhx72TjRpq94hwdl2XWXlgFvJVffTvY92/XbesgwpkwHEtlqKKyZX+sfwGOiBBzpdlVGOG+Lu5JuvTt2TqU0RDth9xxTNIOTqPWHTBcOqMi0ZjWk40yVpeuD1Z+JI9XMwd8tvpbhZ0o+3IxIHascZr37CvWQKq0IWsO4kWDJRD8OCXXcDj43ulVcUPxfIAT5Gu0vPZNCIMzx4lC4JPMW0+YnRy1yngcsWTbr1Jd79F2j4RDNdy8JTm7s5ceqIGjV5iRu0scIiHhX0ZLgm6ad2GB3hOhQA+7IwTWQSvBWg=
  - secure: hU1Ljqt+AlekUmNbLMmIx91ssXVghNz8bzLOLKcRZq4SH3nvF0GIFSBbAYN+7GhiSu41+pKadJxDR2CEIjj5lRqTzHMmaZnbCeVv7aoWwAeGuctRdDmi9UhzX8VMxFmhh6XVBukbSAwR4lFJaWGZvwkxm26A0zU/lvwgDS/BcCNQWWvOnfhXlj2qdH/GwYN+dikREgZpoPGskw155H8OOR02aFvej9PzgK5+c6n8QWjVEP+cpL7AUxEKU7BivPA8STyyS5NNIMrNJnCDzSoV5DxzCXQK24woMYVwIEHFvlBzz3vtegYtLHhqA2O/W0SIwpJ/U5cxOcqgAdyC1xJHprgOlMNhK+WA3vwtGsE329AA7FFYpdkOtqd7RmgD2FDVqyDs8/0ABDQ5jzE4hUUDC/zWHtNY9VYwIDENMh3myjmKW5B/dL16mAD5lmKCYT7x5Un0Un10M/HSpSbpdFxo/Dw2598vVBFYc+yvb0VGAYbpKWmVMMDiaBkj2PjFIB0qZ+b9XjFK5UEEavT0qfn2pxQD8IEfp/la9oc0BUD5s1d+JtS6bGf6G4KsXhhJ/8cTMZexQ1qnIFoe0ZN2fY8sHctQfhVXR6sCoWmrb6atZ2nzSZENEa/45t2LuAkb5R+rIdqPRSoE42CA75scCr8jEZG2TEVUreoxCdYYDwz34s8=
