language: node_js
node_js: stable
before_install:
- stty cols 80
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
env:
  global:
  - secure: cdJjffT/r6ts1tANxflD3bVOy5kxKDZ5CwsoQM5ssjbJn59NGohc23X7SAtcUK5NJnQzCpJOiU4DL0KOwPTDf4w1AKEr8IEwSy1kuvDLDNxYg2IJ+qlWOPdudOyDbK213w2NfT0hze5eQRFZrMmdYikuFnVCsHLGCfTHRb+BHxZZuHlfu5IZLcyKqYFPdMWaYJufM5s6p1O/czXsY4d2IVdPDL9zOw6KEpWbz2kRAGrczALqRnoEcB6aPPGuGBqXmgORkGbHmTqVromVViaOc+NwcrjxLbzJtBIwVV1ZShZwY0MKPJX8TW0Ve5Rg978mkLA39o2MRz8JGIos67LEt4yrpcJJ/EkXSlSMzFae9+Gibh6Vq+NpFc7QTF/yjPzmOqKfCSrPpr6GiNEZMWpigXvcFH32X3i+MtzZt6R8zFVShRJowrDlozfOtZBlwhkDTaBx6sAerErj2sG6szJ8nYadj5MGeqA8dPyD8qrQqGCiB8XYiRwOe+Qzc27T7+ZDWRWPWirEp3eOhxfAF0t+t/CmEWzlylcpLq8R2OUGG5FC3W+zrTswNGOkpxaC1S9EskwacM8nGfu5jepmSJUNrMjD4/NRduSvNUB0bYzm0MPQP1tung7ASrHBlNv7W8252+pV6R7/ulxruefzac44dqVYfoBolE9gE5SpgMGssc4=
  - secure: Qb1x7kZifkO9NJpAYtkFaQXmAolixu3gslPxILzvIvsZOK3gjLzcuHr24MGv8zHL5CNgmUHmi4Tlr3xQghUUY8U2PSv+PQNbNPFEW9jkgKuob34Pp/6NW1dFr9N6q9h8v0nIDkkqbv0Cy2AW/qZ4HWteiGPgaleW7B7I5u7prZvHkkRNsZGTQCVjgx56covdZDttQM/YApvLpTxaNB/AXCvIbTVKsCwDWqsWeEZLz5VCJN1ag/QgVjCLiC8HwQc0kDY7OJ6hmnikLdudzzAknhGqJwPD3fpifcWWN+EgWjCnWYhT5fHWJuyBbxPAbdeR7kvU58m4J+zZmzs1AbVSc+THhvqRq28rseQuKpURtb5mS4QQbuUrgR+KO1LJ9L3IgREmrd9Iys87lhJ6MhMaWfln1fYLDhUsx9mn5WYfrL8SuLMUz5pxGzpCFVxZYk+UdZUQaP8H61kT9JEEhLa2LfrfASw2rvsFZ4id8YOkQeFnwokvspScdie7e/zw+g9OVjAafr6L7q63XKpJqMn25AMOAevFRA6kc17OQfslMcaQ+IU7SZWLGI/zdF82WK+VBIhbwXRlUOOIUej5Qkx8V+8LP07I+vgmx3l21voI1jLaHK5iwqRB4hm4h67t6LUVGzgxtXE54DzwsJmabYgN1jgDzcOpFrtmqjlwzQWbq1I=
  - secure: gJbPqyuEZ94SW8dB5Z8ehfUore2KgWN8FJCLL7eJuKrM+d4OyCr8JM838w1mEmwlnZ1d6C4XtPBW1cfwAR3XVBJwEcgvIDQXsTwgnjpdNxh42yUuYa5YZX7CHF7tc1z13EJlEp9xL/KnhQEIcLx3PkaRQvcvShmB/vFzH0LQGA0qif3MWzAKBYEI04/8sOXUvz/5tUyA55IMrSoiasCV3hzrXeEDkyQUpp7zKdlyYjBhU5BexmmlXmGcL+jP3ysCfe8+m06LacR2qZXB36jcJGc/+mwUY+y7R6aWLDLfzTKvC4/TOmEOIiGp68XuTjRPjGW08pmRogPWTfgRwlCVzinoxX3Yr30xkCxvjcJWuBtvF2yOZlB4hN+7HXIEiKl9uj3T/A3PVLgz1EP25w+GUhXGurWJ+tmDdcqWCAOUkaOwLvKqz797rNwjzX2OuxN9OKa3j0X8Chw0XLeL7BWC/876XH9vJpFZVyYNiK1b0WnbLtegzHpvkXTtlf8r+iMRb66hALJSJd1DTEfNdbmhrTg+ktRiIP9gXlXESj4QdI2pyg8+V/0SOU/LcTo8AZkcMma7QjC+G8cAg+6kM+eFviSXyFyBOlS5eJ27+vxbBMwpVck4BysrN8sP+QgORk7x3en20+AJ74hbEW4TCMfqUdwiV0dnqGQVMiB0vudESyE=
